In [1]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [2]:
import numpy as np

### PCA using linear aljebra

#### Step 1

In [3]:
array = np.array([[1,2,3],[2,3,4],[3,4,5]])
array

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

#### Step 2 : calculate mean of each column 

In [4]:
mean = np.mean(array.T,axis=1)
mean

array([2., 3., 4.])

#### Step 3 : center column vectors of initial matrix by subtracting corresponding mean values

In [5]:
centered_array = array - mean
centered_array

array([[-1., -1., -1.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.]])

#### Step 4 : Create covariance matrix 

In [6]:
cov_mat = np.cov(centered_array.T)
cov_mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Step 5 : Calculate eigen values and eigen vectors of covariance matrix

In [7]:
eig_values,eig_vectors = np.linalg.eig(cov_mat)

In [8]:
print(eig_values)

[ 3.00000000e+00  6.16297582e-33 -7.50963641e-17]


In [9]:
print(eig_vectors)

[[ 5.77350269e-01 -6.51147040e-17  6.09781659e-01]
 [ 5.77350269e-01 -7.07106781e-01 -7.75129861e-01]
 [ 5.77350269e-01  7.07106781e-01  1.65348202e-01]]


#### Step 6 : Project data onto new dimension

In [10]:
array_proj = eig_vectors[:,:2].T.dot(centered_array.T)

In [11]:
array_proj.T

array([[-1.73205081e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 1.73205081e+00,  2.22044605e-16]])

---

### PCA using scikitlearn

In [12]:
import numpy as np
from sklearn.decomposition import PCA

In [13]:
array = np.array([[1,2,3],[2,3,4],[3,4,5]])
pca = PCA(2)
pca.fit(array)
print(pca.components_)
print(pca.explained_variance_)
array_proj = pca.transform(array)
print(array_proj)

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.         -0.70710678  0.70710678]]
[3. 0.]
[[-1.73205081e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.73205081e+00  1.11022302e-16]]


---