In [57]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [58]:
import numpy as np

### PCA using linear aljebra

#### Step 1

In [59]:
array = np.array([[1,2],[2,3],[3,4]])
array

array([[1, 2],
       [2, 3],
       [3, 4]])

#### Step 2 : calculate mean of each column 

In [60]:
mean = np.mean(array.T,axis=1)
mean

array([2., 3.])

#### Step 3 : center column vectors of initial matrix by subtracting corresponding mean values

In [61]:
centered_array = array - mean
centered_array

array([[-1., -1.],
       [ 0.,  0.],
       [ 1.,  1.]])

#### Step 4 : Create covariance matrix 

In [62]:
cov_mat = np.cov(centered_array.T)
cov_mat

array([[1., 1.],
       [1., 1.]])

#### Step 5 : Calculate eigen values and eigen vectors of covariance matrix

In [63]:
eig_values,eig_vectors = np.linalg.eig(cov_mat)

In [64]:
print(eig_values)

[2. 0.]


In [65]:
print(eig_vectors)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


#### Step 6 : Project data onto new dimension

In [66]:
array_proj = eig_vectors.T.dot(centered_array.T)

In [67]:
array_proj.T

array([[-1.41421356,  0.        ],
       [ 0.        ,  0.        ],
       [ 1.41421356,  0.        ]])

---

### PCA using scikitlearn

In [68]:
import numpy as np
from sklearn.decomposition import PCA

In [69]:
array = np.array([[1,2],[2,3],[3,4]])
pca = PCA(2)
pca.fit(array)
print(pca.components_)
print(pca.explained_variance_)
array_proj = pca.transform(array)
print(array_proj)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[2. 0.]
[[-1.41421356e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.41421356e+00  1.11022302e-16]]


---